version: '3.9'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DB_NAME=educa
      - DB_USER=educa_user
      - DB_PASSWORD=educa_pass
      - DB_HOST=db
      - DB_PORT=5432    
  
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: educa
      POSTGRES_USER: educa_user
      POSTGRES_PASSWORD: educa_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:5.0.4
    ports:
      - "6379:6379"

volumes:
  pgdata:
